_target_: network.unet_2d_goub.UNet2DGOUD
in_nc: 3
out_nc: 3
nf: 64
depth: 4
condition_type: NONE
condition_transform_type: NONE
transform_x:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Normalize
        mean: [0.0]
        std: [0.3]
transform_cond:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Normalize
        mean: [0.0]
        std: [0.3]
inv_transform_x:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Normalize
        mean: [0.0]
        std: [3.333]
prediction_type: X_0