_target_: torch.utils.data.DataLoader
dataset:
  _target_: dataset.celebahq.CelebAHQDataset
  path_data: data/datasets/celebahq/train
  split: train
  n_samples: 27000
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.RandomHorizontalFlip
        p: 0.5
      - _partial_: true
        _target_: transform.random_rot90.random_rotate_90
        p: 0.5
batch_size: 8
num_workers: 0