defaults:
  - _self_
  - measurement_model: mask/clean/thin
  - diffusion: i2sb
  - network: celebahq/unet_2d_i2sb
  - ema_network: default
  - optimizer: adam_default
  - lr_scheduler: multistep_default
  - loss_function: mse
  - dataloader@train_dataloader: celebahq/train
  - dataloader@val_dataloader: celebahq/val
  - metric: all_celebahq
  - wandb: default
  - fabric: single_gpu
  - hydra: default

exp:
  seed: 42
  log_dir: # set during runtime to automatically created dir

  run_func: 
    _target_: experiment.train_diffusion.run

  n_epochs: 256 # 4096 * 128 = 524288 iterations (if iteration == single batch)
  log_frequency: 8 # every this number of batches data is logged to wandb
  validation_frequency: 16 # every this number of epochs validation is performed
  save_frequency: 8 # every this number of epochs checkpoint is saved
  batch_accum: 1
  load_ckpt: