defaults:
  - _self_
  - measurement_model: mask/clean/thin
  - diffusion: sdb
  - sde: celebahq/sdb
  - network: celebahq/unet_2d_pdb
  - ema_network: default
  - optimizer: adam_default
  - lr_scheduler: multistep_default
  - loss_function: l1
  - timestep_sampler: celebahq/sdb/i2sb/uniform
  - variance_schedule: celebahq/sdb_i2sb
  - dataloader@train_dataloader: celebahq/train
  - dataloader@val_dataloader: celebahq/val
  - metric: all_celebahq
  - wandb: default
  - fabric: single_gpu
  - hydra: default

exp:
  seed: 42
  log_dir: # set during runtime to automatically created dir

  run_func: 
    _target_: experiment.train_diffusion.run

  log_assets: false
  eval_ema: false
  n_epochs: 256
  log_frequency: 8 # every this number of batches data is logged to wandb
  validation_frequency: 16 # every this number of epochs validation is performed
  save_frequency: 8 # every this number of epochs checkpoint is saved
  batch_accum: 1
  load_ckpt: