defaults:
  - _self_
  - measurement_model: sr/div2k/clean/default
  - diffusion: sdb
  - sde: div2k/sdb
  - solver: sdb_vp_linear/div2k/euler
  - network: div2k/unet_2d_pdb
  - ema_network: default
  - optimizer: adam_default
  - lr_scheduler: multistep_default
  - loss_function: l1
  - timestep_sampler: div2k/sdb/vp_linear/uniform
  - variance_schedule: div2k/sdb_vp_linear
  - dataloader@train_dataloader: div2k/train
  - dataloader@val_dataloader: div2k/val
  - metric: all_div2k
  - wandb: default
  - fabric: single_gpu
  - hydra: default

exp:
  seed: 42
  log_dir: # set during runtime to automatically created dir

  run_func: 
    _target_: experiment.train_diffusion.run

  log_assets: false
  eval_ema: false
  n_epochs: 256
  log_frequency: 8 # every this number of batches data is logged to wandb
  validation_frequency: 16 # every this number of epochs validation is performed
  save_frequency: 8 # every this number of epochs checkpoint is saved
  batch_accum: 1
  load_ckpt: